version: '3'
services:
  nginx:
    image: "nginx:latest"
    # restart: always
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    links:
      - web

  web:
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    ports:
      - "5000:5000"
    command: gunicorn -c ./conf/gunicorn_config.py run:app
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - web_redis

  web_redis:
    image: "redis:latest"
    container_name: "web_redis"
    restart: always
    hostname: web_redis
    command: redis-server --requirepass ""
    ports:
      - "16379:6379"